---
title: "Client Report - Late Flights & Missing Data (JSON)"
subtitle: "Course DS 250"
author: "[STUDENT NAME]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_json("https://github.com/byuidatascience/data4missing/raw/master/data-raw/flights_missing/flights_missing.json")
```

## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

_A Client has requested this analysis and this is your one shot of what you would say to your boss in a 2 min elevator ride before he takes your report and hands it to the client._

## QUESTION|TASK 1

__Fix all of the varied missing data types in the data to be consistent (all missing values should be displayed as “NaN”).__ In your report include one record example (one row) from your new data, in the raw JSON format. Your example should display the "NaN" for at least one missing value.__  

_I made all missing values np.nans, and display the data in raw json format._

```{python}
# Include and execute your code here
df2 = df.fillna(np.nan)
# df2[(df['airport_code'] == 'ATL')]
df2.num_of_delays_late_aircraft = df2.num_of_delays_late_aircraft.replace(-999,df2.num_of_delays_late_aircraft.mean())
df2[(df['airport_code'] == 'ATL')].head(100)
df2[21:22]
json_data = df2[21:22].to_json()
json_data

# df2 = df[(df['airport_code'] == 'ATL') & (df['month'] == 'March')]
```


## QUESTION|TASK 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours.   

_Relative to number of flights, as is evidenced in the graph, SFO has the longest delays relative to its size as an airport and the highest proportion of delayed flights._

```{python}
# Include and execute your code here
ggplot(df, aes(x='num_of_flights_total', y='num_of_delays_total', color='airport_code')) + geom_point()

df_task2 = df2[['airport_code', 'num_of_flights_total', 'num_of_delays_total', 'minutes_delayed_total']]
df_task2['proportion_of_delayed_flights'] = df.num_of_delays_total / df.num_of_flights_total
df_task2
ggplot(df_task2, aes(x='minutes_delayed_total', y='proportion_of_delayed_flights', color='airport_code')) + geom_point()
```



## QUESTION|TASK 3

__What is the best month to fly if you want to avoid delays of any length?__ Describe the metric you chose and why you chose it to calculate your answer. Include one chart to help support your answer, with the x-axis ordered by month. (To answer this question, you will need to remove any rows that are missing the `Month` variable.)  

_It appears that, by a small margin, March has the lowest proportion of delayed flights across all airports._

```{python}
# Include and execute your code here
df_task3 = df2[['airport_code', 'month', 'num_of_flights_total', 'num_of_delays_total']]
df_task3['proportion_of_delayed_flights'] = df.num_of_delays_total / df.num_of_flights_total
df_task3.groupby('month')
ggplot(df_task3, aes(x='month', y='proportion_of_delayed_flights')) + geom_bar()
```



## QUESTION|TASK 4

According to the BTS website, the “Weather” category only accounts for severe weather delays. Mild weather delays are not counted in the “Weather” category, but are actually included in both the “NAS” and “Late-Arriving Aircraft” categories. __Your job is to create a new column that calculates the total number of flights delayed by weather (both severe and mild).__ You will need to replace all the missing values in the Late Aircraft variable with the mean. Show your work by printing the first 5 rows of data in a table. Use these three rules for your calculations:  

    a. 100% of delayed flights in the Weather category are due to weather  
    a. 30% of all delayed flights in the Late-Arriving category are due to weather  
    a. From April to August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%    

_type your results and analysis here_

```{python}
# Include and execute your code here
# df2['new_weather'] = df2['num_of_delays_weather'] + df2['num_of_delays_late_aircraft'] * .3 + df2[(df['month'] == 'April') | (df['month'] == 'May') | (df['month'] == 'June') | (df['month'] == 'July') | (df['month'] == 'August')] * .4
df2['weather_delays'] = df2.num_of_delays_weather
df2
```


```{python}
# Include and execute your code here
df2['weather_delays'] = df2['weather_delays'] + df2.num_of_delays_late_aircraft * .3
df2
```


```{python}
# Include and execute your code here
# df2['weather_delays'] = df2['weather_delays'] + df2.query('month == "April" or month == "May" or month == "June" or month == "July" or month == "August"') * .4 + df2.query('month == "January" or month == "February" or month == "March" or month == "September" or month == "October" or month == "November" or month == "December"') * .65

for i in range(12):
    if i >= 3 and i <= 7:
        df2['weather_delays'] = df2.num_of_delays_nas * .4
    else:
        df2['weather_delays'] = df2.num_of_delays_nas * .65

df2
```



## QUESTION|TASK 5

__Using the new weather variable calculated above, create a barplot showing the proportion of all flights that are delayed by weather at each airport. Describe what you learn from this graph.__  

_type your results and analysis here_
```{python}
# Include and execute your code here
ggplot(df2, aes(x='airport_code', y='weather_delays')) + geom_bar()
```


---


## STRETCH QUESTION|TASK 1

__Which delay is the worst delay?__ Create a similar analysis as above for Weahter Delay with: Carrier Delay and Security Delay. Compare the proportion of delay for each of the three categories in a Chart and a Table. Describe your results.

_type your results and analysis here_

```{python}
# Include and execute your code here

```

---

